/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/vNJktegB5rO
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { DropdownMenuTrigger, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuCheckboxItem, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import { Badge } from "@/components/ui/badge"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

export function newtable() {
  return (
    <div className="w-full overflow-auto">
      <div className="flex justify-between items-center mb-4">
        <Input className="w-64" placeholder="Search researchers..." type="search" />
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button className="shrink-0" variant="outline">
              <FilterIcon className="w-4 h-4 mr-2" />
              Filter
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent className="w-56">
            <DropdownMenuLabel>Research Areas</DropdownMenuLabel>
            <DropdownMenuSeparator />
            <DropdownMenuCheckboxItem>
              <Badge className="bg-blue-100 text-blue-800" variant="outline">
                Quantum Computing
              </Badge>
            </DropdownMenuCheckboxItem>
            <DropdownMenuCheckboxItem>
              <Badge className="bg-red-100 text-red-800" variant="outline">
                Cryptography
              </Badge>
            </DropdownMenuCheckboxItem>
            <DropdownMenuCheckboxItem>
              <Badge className="bg-green-100 text-green-800" variant="outline">
                Cybersecurity
              </Badge>
            </DropdownMenuCheckboxItem>
            <DropdownMenuCheckboxItem>
              <Badge className="bg-yellow-100 text-yellow-800" variant="outline">
                Machine Learning
              </Badge>
            </DropdownMenuCheckboxItem>
            <DropdownMenuCheckboxItem>
              <Badge className="bg-purple-100 text-purple-800" variant="outline">
                Computer Vision
              </Badge>
            </DropdownMenuCheckboxItem>
            <DropdownMenuCheckboxItem>
              <Badge className="bg-pink-100 text-pink-800" variant="outline">
                Natural Language Processing
              </Badge>
            </DropdownMenuCheckboxItem>
            <DropdownMenuCheckboxItem>
              <Badge className="bg-teal-100 text-teal-800" variant="outline">
                Robotics
              </Badge>
            </DropdownMenuCheckboxItem>
            <DropdownMenuCheckboxItem>
              <Badge className="bg-orange-100 text-orange-800" variant="outline">
                Artificial Intelligence
              </Badge>
            </DropdownMenuCheckboxItem>
            <DropdownMenuCheckboxItem>
              <Badge className="bg-indigo-100 text-indigo-800" variant="outline">
                Human-Robot Interaction
              </Badge>
            </DropdownMenuCheckboxItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </div>
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>Name</TableHead>
            <TableHead>Affiliation</TableHead>
            <TableHead>Research Areas</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          <TableRow>
            <TableCell className="font-medium">Dr. Emily Johnson</TableCell>
            <TableCell>Harvard University</TableCell>
            <TableCell>
              <div className="flex flex-wrap gap-2">
                <Badge className="bg-blue-100 text-blue-800" variant="outline">
                  Quantum Computing
                </Badge>
                <Badge className="bg-red-100 text-red-800" variant="outline">
                  Cryptography
                </Badge>
                <Badge className="bg-green-100 text-green-800" variant="outline">
                  Cybersecurity
                </Badge>
              </div>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="font-medium">Prof. Michael Lee</TableCell>
            <TableCell>Stanford University</TableCell>
            <TableCell>
              <div className="flex flex-wrap gap-2">
                <Badge className="bg-yellow-100 text-yellow-800" variant="outline">
                  Machine Learning
                </Badge>
                <Badge className="bg-purple-100 text-purple-800" variant="outline">
                  Computer Vision
                </Badge>
                <Badge className="bg-pink-100 text-pink-800" variant="outline">
                  Natural Language Processing
                </Badge>
              </div>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="font-medium">Dr. Samantha Brown</TableCell>
            <TableCell>Massachusetts Institute of Technology (MIT)</TableCell>
            <TableCell>
              <div className="flex flex-wrap gap-2">
                <Badge className="bg-teal-100 text-teal-800" variant="outline">
                  Robotics
                </Badge>
                <Badge className="bg-orange-100 text-orange-800" variant="outline">
                  Artificial Intelligence
                </Badge>
                <Badge className="bg-indigo-100 text-indigo-800" variant="outline">
                  Human-Robot Interaction
                </Badge>
              </div>
            </TableCell>
          </TableRow>
        </TableBody>
      </Table>
    </div>
  )
}

function FilterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3" />
    </svg>
  )
}
